services:
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
  web:
    build:
      context: .
    #  target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    # stop_signal: SIGINT
    ports:
      - '8000:8000'
    volumes:
      - .:/code  # With volumes: Essential for development (live editing, hot reloading)
    depends_on:
      - redis
